version: '2'
services:

  nginx:
    image: nginx
    ports:
      - "2610:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
      - service-stock-mysql

  php:
    build: ./docker/php
    container_name: service-stock-php
    working_dir: /var/www
    volumes:
      - .:/var/www
  service-stock-mysql:
    image: mysql:5.7

    ports:
      - "3306:3306"
      - "33061:3306"

    volumes:
      - ./database.sql:/database.sql
      - ./db:/var/lib/mysql
    
    command: --init-file /database.sql    
    environment:
        - MYSQL_ROOT_PASSWORD=root
    links:
        - php
        
# http://ubuntudev:2610/api/stockinterface        